services:
  mongo-express:
    image: mongo-express:1-20
    container_name: wp-sentinel-mongo-gui
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: "27017"
      ME_CONFIG_MONGODB_ADMINUSERNAME: wpsentinel
      ME_CONFIG_MONGODB_ADMINPASSWORD: "Kx9$$mQ7vLp2wNrT4!bZj"
      ME_CONFIG_BASICAUTH_USERNAME: sentinel_admin
      ME_CONFIG_BASICAUTH_PASSWORD: "Gu!4dPnL8$vXr3KmW7qJ"
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - wp-sentinel
